---
title: Stackbit Exto Theme
baseURL: "/"
params:
  color_scheme: light
  accent_color: pink
  header:
    title: Walker Kehoe
    has_nav: true
    logo_img: ''
  footer:
    content: "&copy; Walker Kehoe. All rights reserved."
    links: []
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
menu:
  main:
  - url: https://www.linkedin.com/in/walkerkehoe/
    name: LinkedIn
    weight: 6
  - name: Resumé
    weight: 5
