---
title: Stackbit Exto Theme
baseURL: "/"
params:
  color_scheme: light
  accent_color: pink
  header:
    title: Walker Kehoe
    has_nav: true
  footer:
    content: "&copy; Walker Kehoe. All rights reserved."
    links: []
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
